import type { Metadata } from "next";
import { Poppins, Source_Code_Pro } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";

const source_sans_3 = Source_Code_Pro({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Count Word by Yusif Aliyev",
  description: "Generated by create next app",
  authors: [{ name: "Yusif Aliyev", url: "https://yusifaliyevpro.com/" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${source_sans_3.className} ${poppins.variable} min-h-svh`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
